#!/usr/bin/bash

if [ $# -eq 1 ]; then
    echo "Download Pattern $1"
    wget "$1" -P ./assets/
fi

echo "Update the assets javascript files"

output_file="./assets/index.ts"

echo "// This file is autogenerated by 'make_assets.sh'" > $output_file
echo "" >> $output_file

files=(./assets/*.cells)

i=0
text=""
for f in "${files[@]}"; do
    i=$(( i + 1 ))
    filename=$(basename -- "$f")

    echo "import * as cell${i} from \"./${filename}\";" >> $output_file
done

echo "" >> $output_file
echo "export const PATTERNS = [" >> $output_file

i=0
for f in "${files[@]}"; do
    i=$(( i + 1 ))
    echo "  cell${i} as string," >> $output_file
done

echo "];" >> $output_file

output_file="./assets/index.d.ts"

echo "declare module \"*.cells\" {}" > $output_file

exit 0
