// This file is autogenerated by 'make_assets.sh'

import * as cell1 from "./blinker.cells";
import * as cell2 from "./block.cells";
import * as cell3 from "./cell.cells";
import * as cell4 from "./eater1.cells";
import * as cell5 from "./glider.cells";
import * as cell6 from "./gosperglidergun.cells";
import * as cell7 from "./herschel.cells";
import * as cell8 from "./pulsar.cells";
import * as cell9 from "./switchengine.cells";

export const PATTERNS = [
  cell1 as string,
  cell2 as string,
  cell3 as string,
  cell4 as string,
  cell5 as string,
  cell6 as string,
  cell7 as string,
  cell8 as string,
  cell9 as string,
];
