// This file is autogenerated by 'make_assets.sh'

import * as cell1 from "./3c10piwave.cells";
import * as cell2 from "./acorn.cells";
import * as cell3 from "./bananaspark.cells";
import * as cell4 from "./blinker.cells";
import * as cell5 from "./block.cells";
import * as cell6 from "./chickenwire.cells";
import * as cell7 from "./dot.cells";
import * as cell8 from "./eater1.cells";
import * as cell9 from "./glider.cells";
import * as cell10 from "./gosperglidergun.cells";
import * as cell11 from "./herschel.cells";
import * as cell12 from "./lidka.cells";
import * as cell13 from "./pulsar.cells";
import * as cell14 from "./switchengine.cells";
import * as cell15 from "./unix.cells";
import * as cell16 from "./zebrastripes.cells";

export const PATTERNS = [
  cell1 as string,
  cell2 as string,
  cell3 as string,
  cell4 as string,
  cell5 as string,
  cell6 as string,
  cell7 as string,
  cell8 as string,
  cell9 as string,
  cell10 as string,
  cell11 as string,
  cell12 as string,
  cell13 as string,
  cell14 as string,
  cell15 as string,
  cell16 as string,
];
